# .github/workflows/pbi-capacity.yml
name: Control Power BI Embedded Capacity

on:
  schedule:
    # Encender: 08:00, 13:00, 16:00
    - cron: '0 11 * * 1-5'  # 08:00 Argentina = 11:00 UTC
    - cron: '0 16 * * 1-5'
    - cron: '0 19 * * 1-5'
    # Apagar: 10:00, 14:30, 17:00
    - cron: '0 13 * * 1-5'
    - cron: '30 17 * * 1-5'
    - cron: '0 20 * * 1-5'

jobs:
  control-capacity:
    runs-on: ubuntu-latest
    steps:
      - name: Configurar PowerShell
        uses: actions/setup-powershell@v2

      - name: Descargar script
        uses: actions/checkout@v4

      - name: Ejecutar acción (Start o Stop)
        run: |
          pwsh scripts/capacity_control.ps1
        env:
          TENANT_ID: ${{ secrets.TENANT_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          CAPACITY_ID: ${{ secrets.CAPACITY_ID }}
          # Determinar si es "start" o "stop" según la hora
          CAPACITY_ACTION: ${{ github.event.schedule == '0 11 * * 1-5' || github.event.schedule == '0 16 * * 1-5' || github.event.schedule == '0 19 * * 1-5' && 'start' || 'stop' }}
