name: Controlar Capacidad Power BI

on:
  workflow_dispatch:
  schedule:
    # Encender a las 07:20
    - cron: '20 7 * * 1-5'
    # Apagar a las 09:00
    - cron: '0 9 * * 1-5'
    # Encender a las 12:00
    - cron: '0 12 * * 1-5'
    # Apagar a las 14:30
    - cron: '30 14 * * 1-5'
    # Encender a las 15:45
    - cron: '45 15 * * 1-5'
    # Apagar a las 17:00
    - cron: '0 17 * * 1-5'

jobs:
  controlar-capacidad:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configurar acción (start o stop)
        shell: pwsh
        run: |
          $hora = (Get-Date).ToUniversalTime().AddHours(-3).ToString("HH:mm")
          if ($hora -eq "07:20" -or $hora -eq "12:00" -or $hora -eq "15:45") {
            echo "CAPACITY_ACTION=start" >> $env:GITHUB_ENV
          } elseif ($hora -eq "09:00" -or $hora -eq "14:30" -or $hora -eq "17:00") {
            echo "CAPACITY_ACTION=stop" >> $env:GITHUB_ENV
          } else {
            echo "CAPACITY_ACTION=skip" >> $env:GITHUB_ENV
          }

      - name: Ejecutar script PowerShell
        if: env.CAPACITY_ACTION != 'skip'
        run: ./scripts/capacity_control.ps1
        env:
          TENANT_ID: ${{ secrets.TENANT_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          CAPACITY_ID: ${{ secrets.CAPACITY_ID }}
          CAPACITY_ACTION: ${{ env.CAPACITY_ACTION }}
